version: '3.8'
services:
  dynamodb-local:
    image: "zestyco/dynamodb-challenge:amd"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
  
  zesty-secret-retriever:
    image: "khalilj/zesty-secret-retriever:latest"
    build: .
    container_name: zesty-secret-retriever
    ports:
      - "8080:80"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
      CODE_NAME: ${CODE_NAME}
    depends_on:
      - dynamodb-local

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: "us-west-2"
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local
