name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: "khalilj/zesty-secret-retriever"
      DOCKER_USER: "khalilj"

    steps:
    - uses: actions/checkout@v3
    
    - name: Get git short sha
      id: git_sha
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT\
      
    - name: Build the Docker image
      run: docker build -t ${{ env.DOCKER_REPOSITORY }}:latest .

    - name: Test
      env:
        CODE_NAME: ${{ secrets.CODE_NAME }}
      run: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
        chmod 755 ./docker-compose
        ./docker-compose up -d --wait
        curl http://127.0.0.1:8080/health
        ./docker-compose down
    
    - name: Push to Docker Registry
      run: |
        echo ${{ secrets.DOCKER_REPOSITORY_PASS }} | docker login --username ${{ env.DOCKER_USER }} --password-stdin
        docker tag ${{ env.DOCKER_REPOSITORY }}:latest ${{ env.DOCKER_REPOSITORY }}:${{ steps.git_sha.outputs.sha_short }}
        docker push ${{ env.DOCKER_REPOSITORY }}:latest
        docker push ${{ env.DOCKER_REPOSITORY }}:${{ steps.git_sha.outputs.sha_short }}
